backend:
  name: git-gateway
  branch: main
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    description: '{{path}}'
    folder: 'content/'
    create: true
    slug: '{{slug}}'
    nested:
      depth: 10
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    meta: { path: { widget: string, label: 'Path', index_file: '_index' } }
