backend:
  name: git-gateway
  branch: main
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'content/'
    create: true
    slug: '{{slug}}'
    summary: '{{title}} | /{{dirname}}'
    nested:
      depth: 10
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Custom CSS'
        name: 'custom_css'
        required: false
        widget: 'code'
        default_language: 'css'
        allow_language_selection: false
        output_code_only: true
      - label: 'Flex column layout'
        name: 'flex_column'
        required: false
        widget: 'boolean'
    meta: { path: { widget: string, label: 'Path', index_file: '_index' } }
